### PR TITLE
robot: Always update odometry before localising

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by OliverW10** [comment]
I think I was seeing crashes in teleop, would it be an idea to put an update_odometry() is the chassis set_pose as that would clear the pose estimators history buffer

**Comment by fotnitfpro000** [comment]
uh i dont think so davo

no way jose

no way jodavo!!!!!

**Comment by auscompgeek** [comment]
> would it be an idea to put an update_odometry() is the chassis set_pose as that would clear the pose estimators history buffer

The issue with the pose estimator history buffer should've been fixed in 2023.4.1 so there must be something else wrong there.

The documentation for addVisionMeasurement implies that update must be called at least as frequently as addVisionMeasurement, so we're already holding it wrong as it is now.

**Comment by james-ward** [comment]
@auscompgeek if we are doing it wrong could you please fix while we work on the other stuff??

**Comment by auscompgeek** [comment]
@james-ward this PR is the fix for that issue.

**Review by james-ward — APPROVED** [review]

**Pull request merged**
