### PR TITLE
fuzz_test: Add test mode test

### PR DESCRIPTION
**Pull request by auscompgeek**
This adds a chaos-monkey-at-the-driver-station test for test mode.

### CODE REVIEW

**Comment by auscompgeek** [comment]
not really sure why CI is hanging when it runs within half a minute on my laptop :upside_down_face:

**Comment by LucienMorey** [comment]
Turns out it just needs me to retrigger it lmao

**Comment by auscompgeek** [comment]
wtf

**Comment by auscompgeek** [comment]
Well, I guess if this is working in CI after a few tries now...

**Review by LucienMorey — APPROVED** [review]

**Pull request merged**
